# Generated by Django 5.1.3 on 2024-12-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_custom_lookups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num',
            field=models.IntegerField(default=-100),
        ),
    ]
