# Generated by Django 5.1.3 on 2024-12-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_migrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
