# Generated by Django 5.1.3 on 2024-12-14 19:30

from django.db import migrations, models

def add_default_author(apps, schema_editor):
    Book = apps.get_model('new_migrations', 'Book')

    for i in Book.objects.all():
        if i.content:
            i.author = i.content
        else:
            i.author = "Unknown"
        
        i.save()
            


class Migration(migrations.Migration):

    dependencies = [
        ('new_migrations', '0002_alter_book_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(add_default_author),
    ]
