# Generated by Django 5.1.3 on 2024-12-24 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_database_functions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
