# Generated by Django 5.1.3 on 2024-12-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_database_functions', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
