# Generated by Django 5.1.3 on 2024-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_managers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('C', 'Comedy'), ('F', 'Fantasy')], default='C', max_length=1),
        ),
    ]
