# Generated by Django 5.1.4 on 2024-12-31 03:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadsclass',
            name='file_2',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/uploads'), upload_to=''),
        ),
    ]
