# Generated by Django 5.1.5 on 2025-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ManyToManyField(related_name='books', to='admin_site.publisher'),
        ),
    ]
