# Generated by Django 5.1.3 on 2024-12-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='product',
        ),
    ]
